name: myproject
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^2.1.0

  #image carousel
  flutter_image_slideshow: ^0.1.2

  # networking
  dio_http_cache: ^0.3.0
  http_parser: ^4.0.0

  #  hydrated_bloc: ^7.0.1

  json_annotation: ^4.1.0
  simple_animations: ^4.0.1
  bloc: ^7.2.1
  http: ^0.13.4
  flutter_bloc: ^7.3.0
  intl: ^0.17.0
  crypto: ^3.0.1
  flutter_svg: ^0.23.0+1
  progress_dialog: ^1.2.4
  shared_preferences: ^2.0.8
  streaming_shared_preferences: ^2.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  auto_size_text: ^3.0.0-nullsafety.0
  #firebase_crashlytics: 2.0.0
  image_picker: ^0.8.4+2
  flutter_linkify: ^5.0.2
  path_provider: ^2.0.5
  file_picker: ^4.1.4
  file: ^6.1.2
  mime: ^1.0.1
  share: ^2.0.4
  equatable: ^2.0.3
  uuid: ^3.0.6
  pull_to_refresh: ^2.0.0
  get_it: ^7.2.0
  uni_links: ^0.5.1
  email_validator: ^2.1.17
  carousel_slider: ^4.1.1
  graphql_flutter: ^5.0.0
  flutter_html: ^2.2.1
  cached_network_image: ^3.2.2
  dotted_line: ^3.1.0
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.0
  google_maps_webservice: ^0.0.19
  diacritic: ^0.1.3
  modal_bottom_sheet: ^2.1.2
  flutter_animated_dialog: ^2.0.1
  connectivity_plus: ^1.1.0
  url_launcher: ^6.1.5
  flutter_phone_direct_caller: ^2.1.1
  flutter_local_notifications: ^9.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/


